### PR TITLE
Build dev docker-images

### PR DESCRIPTION
**Pull request by tboegner**
Currently we have no separation between services, a push to master triggers build and push to registry for all services.

### CODE REVIEW

**Comment by adewes** [comment]
Does this make the existing workflow (https://github.com/iris-connect/eps/blob/master/.github/workflows/build-and-push-docker-images.yml) obsolete?

**Comment by lucky-lusa** [comment]
I think we might not need this. There is no need to have develop images for rapid deployment of eps. I think we should always update eps manually on our gateways.

**Comment by tboegner** [comment]
> Does this make the existing workflow (https://github.com/iris-connect/eps/blob/master/.github/workflows/build-and-push-docker-images.yml) obsolete?
No, build-and-push-docker-images.yml is for publishing new release versions. The new workflow was intended for current development versions.

**Comment by tboegner** [comment]
> There is no need to have develop images for rapid deployment of eps.

What about Proxy-Service and Service-Directory, should they also be updated manually?

**Comment by adewes** [comment]
Do we still need this with the changes to the release process that we've recently made or can we close this?

**Comment by lucky-lusa** [comment]
No, we do not need this. I will close it.

**Pull request closed without merging**
